### ISSUE TITLE
Move configuration items out of .sh scripts and into config?

### ISSUE THREAD

**Issue by NullReferenceError** [bhavenga/pwrstatd_scripts#1]
Thanks for making these! Very frustrating that the Cyberpower scripts that come with the software don't seem to work at all, and are not maintained. Thanks for fixing them up. Working perfectly in Debian 10 also.

I may take the time to do this, but I think the configuration items (email addresses, Enabling of email, recipient name, UPS Location) could be moved into the .conf file? Could help with maintainability and make it easier for others to pull in.

**Comment by bhavenga** [comment]
Glad this actually helped someone.

Agreed; I've been meaning to clean this up and split it out with a config file. Maybe I'll finally get around to it.
